config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :pics do
    member do
      put "like", to: "pics#upvote"
    end
  end
  root "pics#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/pic.rb
class Pic < ApplicationRecord
  acts_as_votable
  belongs_to :user

  has_attached_file :image, styles: { medium: "300x300>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/

end

app/models/user.rb
class User < ApplicationRecord
  has_many :pics

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pics_controller.rb
class PicsController < ApplicationController
  before_action :find_pic, only: [:show, :edit, :update, :destroy, :upvote]
  before_action :authenticate_user!, except: [:index, :show]

  def index
    @pics = Pic.all.order("created_at DESC")
  end

  def show
    @pic = Pic.find(params[:id])
  end

  def new
    @pic = current_user.pics.build
  end

  def create
    @pic = current_user.pics.build(pic_params)

    if @pic.save
      redirect_to @pic, notice: "Yesss! it was posted!"
    else
      render 'new'
    end
  end

  def edit

  end

  def update
    if @pic.update(pic_params)
      redirect_to @pic, notice: "Congrats! Pic was updated!"
    else
      render "edit"
    end
  end

  def destroy
    @pic.destroy
    redirect_to root_path
  end

  def upvote
    @pic.upvote_by current_user
    redirect_back(fallback_location: root_path)
  end

  private

  def pic_params
    params.require(:pic).permit(:title, :description, :image)
  end

  def find_pic
    @pic = Pic.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pics_helper.rb
module PicsHelper
end

app/views/layouts/application.html.haml
!!! 5
%html
%head
  %title Instagramm
  = csrf_meta_tags
  = csp_meta_tag
  = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
  = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'

%body
  %nav.navbar.navbar-inverse
    .container
      .navbar-brand= link_to "Instagramm", root_path

      - if user_signed_in?
        %ul.nav.navbar-nav.navbar-left
          %li= link_to "Gram It!", new_pic_path
          %li= link_to "Settings", edit_user_registration_path
          %li= link_to "Sign Out", destroy_user_session_path, method: :delete
      - else
        %ul.nav.navbar-nav.navbar-left
          %li= link_to "Join", new_user_registration_path
          %li= link_to "Log In", new_user_session_path

  .container
    -flash.each do |name, msg|
      =content_tag :div, msg, class: "alert alert-info"

  = yield

app/views/pics/_form.html.haml
= simple_form_for @pic, html: { multipart: true } do |f|
  - if @pic.errors.any?
    #errors
      %h2
        = pluralize(@pic.errors.count, "error")
        prevented this Pic from saving
      %ul
        - @pic.errors.full_messages.each do |msg|
          %li= msg

  .form-group
    = f.input :image, input_html: { class: 'form-control' }
  .form-group
    = f.input :title, input_html: { class: 'form-control' }
  .form-group
    = f.input :description, input_html: { class: 'form-control' }

  = f.button :submit, class: "btn btn-info"

app/views/pics/edit.html.haml
#dit_page.col-md-8.col-md-offset-2
  .row
    .panel.panel-default
      .panel-heading
        %h1 Fix Pic
      .panel-body
        .current_image
          %strong.center Right Now
          = image_tag @pic.image.url(:medium)
        = render 'form'

app/views/pics/index.html.haml
.col-md-6.col-md-offset-3
  #pics.transitions-enabled
    - @pics.each do |pic|
      .box.panel.panel-default
        = link_to (image_tag pic.image.url(:medium)), pic
        %h2= link_to pic.title, pic

app/views/pics/new.html.haml
.col-md-8.col-md-offset-2
  .row
    .panel.panel-default
      .panel-heading
        %h1 Post Pic
      .panel-body
        = render 'form'

app/views/pics/show.html.haml
#pic_show.row
  .col-md-6.col-md-offset-3
    .panel.panel-default
      .panel.heading.pic_image
        = image_tag @pic.image.url(:medium)
      .panel-body
        %h1= @pic.title
        %p= @pic.description
      .panel-footer
        .row
          .col-md-6
            %p.user
              Pic By
              = @pic.user.email
          .col-md-6
            .btn-group.pull-right
              = link_to like_pic_path(@pic), method: :put, class: "btn btn-default" do
                = fa_icon "thumbs-up"
                = @pic.get_upvotes.size

              - if user_signed_in?
                = link_to "Edit", edit_pic_path, class: "btn btn-info"
                = link_to "Delete", pic_path, method: :delete, data: { confirm: "Are you sure? "}, class: "btn btn-danger"